export async function getPost1() {
    await new Promise((resolve) => setTimeout(resolve, 0));
    return {
    allpost : [
      { 
        id: 1,
        route: "yamaha-r3-1302",
        name: "Yamha R3",
        name2: "Yamha R3 Black",
        ads: "sports",
        type: "bikes",
        ev: "no",
        price: "₹3 59 900*",
        topspeed: "185",
        mileage: "25-30",
        permileage: "km/l",
        servicecost: "₹2000 - ₹4500",
        specs: "Specification of Yamaha R3",
        metatitle: "Yamaha R3: Track-Ready Sportbike - Full specs, mileage, top speed", 
        metadesc: "Yamaha R3 2025's top speed, acceleration, features, mileage, service cost, fuel efficiency, and maintenance costs. ", 
        keywords: ["Yamaha R3 2025","Yamaha R3 2025 price","Yamaha R3 2025 specs","Yamaha R3 2025 top speed","Yamaha R3 2025 features","Yamaha R3 2025 mileage","Yamaha R3 2025 review","Yamaha R3 2025 vs KTM RC 390","Yamaha R3 2025 maintenance cost","Yamaha R3 2025 service schedule"],
        publishedAt: "2025-02-13T13:20:00+05:30",
        modifiedAt: "2025-02-13T13:20:00+05:30",
        h1: "Yamaha R3: Track-Ready Sportbike",
        img: "/bikes/yamaha-r3-2025-1302.webp",
        img2: "/bikes/yamaha-r3-2025-1302-2.webp",
        subh1: "Yamaha R3 - Specs, top speed, mileage ",
        desc: "Yamaha has once again raised the bar in the entry-level Race Track bike segment with the launch of the Yamaha R3 2025. entry-level Race Track bike segment with the launch of the Yamaha R3 2025",
        desc2: "With its aggressive styling inspired by Yamaha's MotoGP machines and a lightweight chassis for superior handling,",
        desc3: "the 2025 Yamaha R3 is set to dominate the streets.",
        headingone: "Engine & Performance",
        tableonehead: ["Feature","Specification"],
        tableone: [
                    { id: 1,feature: "Engine Type", col1: "4-stroke, 2-cylinder, Liquid-cooled, DOHC, 4-valves"},
                    { id: 2,feature: "Displacement", col1: "321cc"},
                    { id: 3,feature: "Max Power", col1: "30.9 kW (42.0 PS) @ 10,750 rpm"},
                    { id: 4,feature: "Max Toque", col1: "29.5 Nm (3.0 kgfm) @ 9,000 rpm"},
                    { id: 5,feature: "Bore & Stroke", col1: "68.0 mm x 44.1 mm, 11.2 : 1 ratio"},
                    { id: 6,feature: "Transmission", col1: "Constant Mesh, 6-speed"},
                  ],
        headingtwo: "Braking & Suspension",
        tabletwohead: ["Feature","Specification"],
        tabletwo: [
                    { id: 1,feature: "Front Brake", col1: "Hydraulic single disc, 298 mm"},
                    { id: 2,feature: "Rear Brake", col1: "Hydraulic single disc, 220 mm"},
                    { id: 3,feature: "Front Suspension", col1: "Telescopic Upside Down Fork (USD Fork)"},
                    { id: 4,feature: "Rear Suspension", col1: "Swingarm"},
                    { id: 5,feature: "Front Tyre", col1: "110/70 R17M/C 54H Tubeless"},
                    { id: 5,feature: "Rear Tyre", col1: "140/70 R17M/C 66H Tubeless"},
                  ],
        headingthree: "Dimensions & Chassis",
        tablethreehead: ["Feature","Specification"],
        tablethree: [
                    { id: 1,feature: "Frame", col1: "Diamond"},
                    { id: 2,feature: "Ground clearance", col1: "160 mm"},
                    { id: 3,feature: "Seat Height", col1: "780 mm"},
                    { id: 4,feature: "Kerb Weight", col1: "169 kg"},
                    { id: 5,feature: "Fuel Tank", col1: "14 L"},
                  ],
        headingfour: "Yamaha R3 2025 Features & Electronics",
        listfourtype : "list-disc",
        listfour: [
          {id: 1, head: "", para: "321cc liquid-cooled, parallel-twin engine"},
          {id: 2, head: "", para: "6-speed gearbox with assist & slipper clutch"},
          {id: 3, head: "", para: "Dual-channel ABS for enhanced safety"},
          {id: 4, head: "", para: "USD (Upside-Down) front forks for better handling"},
          {id: 5, head: "", para: "Lightweight steel frame for agile performance"},
          {id: 6, head: "", para: "LED headlights and taillights for modern styling"},
          {id: 7, head: "", para: "Digital LCD instrument cluster"},
          {id: 8, head: "", para: "Bluetooth connectivity (Yamaha Y-Connect app)"},
          {id: 9, head: "", para: "Traction control system (TCS)"},
          {id: 10, head: "",para: "Riding modes – Eco, Sport"},
        ],
        headingfive: " Top Speed & Acceleration",
        listfivetype : "list-disc",
        listfive: [
          {id: 1, head: "", para: "Top Speed: 185 km/h (Approx.)"},
          {id: 2, head: "", para: "0-100 km/h Acceleration: 5.5 seconds"},
        ],
        parafive2: "Note : ",
        parafive3: "claimed 180 kmph Top Speed, Your weight and wind direction is perfect, you will reach 190 kmph",
        headingsix: " Mileage & Fuel Efficiency",
        listsixtype : "list-disc",
        listsix: [
          {id: 1, head: "", para: "Mileage: 25-30 km/l (Approx)"},
          {id: 2, head: "", para: "Fuel Tank Capacity: 14 Liters"},
          {id: 3, head: "", para: "Riding Range: 350-400 km on a Full tank"},
        ],
        headingseven: " Price & Variants",
        tablesevenhead: ["Variants","Expected Price (Ex-Showroom)"],
        tableseven: [
                    { id: 1,feature: "Yamaha Black", col1: "₹3 59 900"},
                    { id: 2,feature: "Icon Blue", col1: "₹3 59 900"},
                  ],
        listseventype: "list-disc",
        listseven: [
          {id: 1, head: "", para: "On-Road Price around 4 lakhs"},
        ],
        paraseven2: "Note: ",
        paraseven3: "Prices may vary based on location and dealer",
        headingeight: "Service & Maintenance Cost",
        listeighttype : "list-disc",
        listeight: [
          {id: 1, head: "", para: "First Service (1,000 km or 1 month) - ₹2,000"},
          {id: 2, head: "", para: "Second Service (5,000 km or 6 months) - ₹3,000"},
          {id: 3, head: "", para: "Annual Service Cost - ₹5,500"},
          {id: 4, head: "", para: "Brake Pad Replacement - ₹1,800 (front), ₹1,200 (rear)"},
          {id: 5, head: "", para: "Engine Oil Change - ₹1,500"},
          {id: 6, head: "", para: "Chain & Sprocket Replacement - ₹4,500"},
        ],
        headingnine: "✔ Pros & ✘ Cons",
        listninetype : "",
        listnine: [
          {id: 1, head: "PROS:", para: ""},
          {id: 2, head: "", para: "✔ Powerful and refined 321cc engine"},
          {id: 3, head: "", para: "✔ Lightweight and agile handling"},
          {id: 4, head: "", para: "✔ Excellent braking performance with ABS"},
          {id: 5, head: "", para: "✔ LED lighting and modern electronics"},
          {id: 6, head: "", para: "✔ Sporty and aggressive design"},
          {id: 7, head: "CONS:", para: ""},
          {id: 8, head: "", para: "✘ Slightly expensive compared to rivals"},
          {id: 9, head: "", para: "✘ No quick-shifter feature"},
          {id: 10, head: "",para: "✘ Pillion seat comfort is limited"},
        ],
        headingten: "Why Should You Choose the Yamaha R3?",
        paraten1: "The Yamaha R3 is built for riders who crave performance and style. ",
        paraten2: "Whether you are commuting daily, hitting the highways, or exploring the racetrack, this bike excels in all aspects.",
        paraten3: "If you're looking for a stylish, reliable, and fun-to-ride machine that delivers both speed and efficiency, the Yamaha R3 2025 is undoubtedly a great choice.",
        headingeleven: "Conclusion",
        paraeleven1: "Yamaha has done an outstanding job with the 2025 R3, making it ",
        paraeleven2: " refined, stylish, and performance-oriented than ever before. ",
        paraeleven3: "Its aggressive styling, premium build quality, and race-inspired DNA make it a top contender in the 300cc sportbike segment.",
        paratwelve1: "For riders looking for an everyday sports bike that balances",
        paratwelve2: " power, agility, and efficiency, ",
        paratwelve3: "the Yamaha R3 2025 is a perfect fit. While it comes at a slightly premium price, the overall riding experience justifies every penny spent. If you’re in the market for a high-performance yet practical sportbike, the Yamaha R3 2025 is worth considering.",
        headingthirteen: "FAQs - Yamaha R3",
        listthirteentype : "list-disc",
        listthirteen: [
          {id: 1, head: " What is the top speed of the Yamaha R3 2025?", para: "The Yamaha R3 2025 has a top speed of approximately 180 km/h."},
          {id: 2, head: "What is the fuel efficiency of the Yamaha R3 2025?", para: "It offers a mileage of around 25-30 km/l."},
          {id: 3, head: "Does the Yamaha R3 2025 have ABS?", para: "Yes, it comes with dual-channel ABS as standard."},
          {id: 4, head: "What is the price of the Yamaha R3 2025 in India?", para: "The starting price of the Yamaha R3 2025 is ₹4,65,000 (ex-showroom)."},
          {id: 5, head: "How often should I service the Yamaha R3 2025?", para: "The first service is at 1,000 km, and then every 5,000 km or 6 months thereafter."},
        ],
        keysearch : ["Yamaha R3 2025","Yamaha R3 2025 price","Yamaha R3 2025 specs","Yamaha R3 2025 top speed","Yamaha R3 2025 features","Yamaha R3 2025 mileage","Yamaha R3 2025 review","Yamaha R3 2025 vs KTM RC 390","Yamaha R3 2025 maintenance cost","Yamaha R3 2025 service schedule"],
        full: "Yamaha R3: Best Race Track Bike Yamaha R3 2025 - Specs, top speed, mileage February 13, 2025 by Arunzed Yamaha has once again raised the bar in the entry-level Race Track bike segment with the launch of the Yamaha R3 2025. With its aggressive styling inspired by Yamaha's MotoGP machines and a lightweight chassis for superior handling, the 2025 Yamaha R3 is set to dominate the streets. Yamha R3 2025 Pricing, Top Speed, Mileage and service cost Price : ₹3 59 900* (Ex) Top Speed : 185 kmph Mileage : 25-30 km/l Serive cost : ₹2000 - ₹4500 Note: CLICK HERE or SWIPE DOWN to read more about the Detailed Explaination of this reviews Specification of Yamaha R3 Engine & Performance Feature Specification Engine Type 4-stroke, 2-cylinder, Liquid-cooled, DOHC, 4-valves Displacement 321cc Max Power 30.9 kW (42.0 PS) @ 10,750 rpm Max Toque 29.5 Nm (3.0 kgfm) @ 9,000 rpm Bore & Stroke 68.0 mm x 44.1 mm, 11.2 : 1 ratio Transmission Constant Mesh, 6-speed Braking & Suspension Feature Specification Front Brake Hydraulic single disc, 298 mm Rear Brake Hydraulic single disc, 220 mm Front Suspension Telescopic Upside Down Fork (USD Fork) Rear Suspension Swingarm Front Tyre 110/70 R17M/C 54H Tubeless Rear Tyre 140/70 R17M/C 66H Tubeless Dimensions & Chassis Feature Specification Frame Diamond Ground clearance 160 mm Seat Height 780 mm Kerb Weight 169 kg Fuel Tank 14 L Yamaha R3 2025 Features & Electronics 321cc liquid-cooled, parallel-twin engine 6-speed gearbox with assist & slipper clutch Dual-channel ABS for enhanced safety USD (Upside-Down) front forks for better handling Lightweight steel frame for agile performance LED headlights and taillights for modern styling Digital LCD instrument cluster Bluetooth connectivity (Yamaha Y-Connect app) Traction control system (TCS) Riding modes – Eco, Sport Top Speed & Acceleration Top Speed: 185 km/h (Approx.) 0-100 km/h Acceleration: 5.5 seconds Note : claimed 180 kmph Top Speed, Your weight and wind direction is perfect, you will reach 190 kmph Yamha R3 2025 Yamaha R3: Best Race Track Bike Mileage & Fuel Efficiency Mileage: 25-30 km/l (Approx) Fuel Tank Capacity: 14 Liters Riding Range: 350-400 km on a Full tank Price & Variants Variants Expected Price (Ex-Showroom) Yamaha Black ₹3 59 900 Icon Blue ₹3 59 900 On-Road Price around 4 lakhs Note: Prices may vary based on location and dealer Yamaha R15M 2025 Yamaha R15M Track-Ready Sportbike Service & Maintenance Cost First Service (1,000 km or 1 month) – ₹2,000 Second Service (5,000 km or 6 months) – ₹3,000 Annual Service Cost – ₹5,500 Brake Pad Replacement – ₹1,800 (front), ₹1,200 (rear) Engine Oil Change – ₹1,500 Chain & Sprocket Replacement – ₹4,500 ✔ Pros & ✘ Cons PROS: ✔ Powerful and refined 321cc engine ✔ Lightweight and agile handling ✔ Excellent braking performance with ABS ✔ LED lighting and modern electronics ✔ Sporty and aggressive design CONS: ✘ Slightly expensive compared to rivals ✘ No quick-shifter feature ✘ Pillion seat comfort is limited Yamaha R15 V4 Yamaha R15 V4 - A Sportbike with MotoGP DNA Why Should You Choose the Yamaha R3 2025? The Yamaha R3 2025 is built for riders who crave performance and style. Whether you are commuting daily, hitting the highways, or exploring the racetrack, this bike excels in all aspects. If you're looking for a stylish, reliable, and fun-to-ride machine that delivers both speed and efficiency, the Yamaha R3 2025 is undoubtedly a great choice. Conclusion Yamaha has done an outstanding job with the 2025 R3, making it refined, stylish, and performance-oriented than ever before. Its aggressive styling, premium build quality, and race-inspired DNA make it a top contender in the 300cc sportbike segment. KTM RC 390 KTM RC 390 2025 - A Game Changer Mechine For riders looking for an everyday sports bike that balances power, agility, and efficiency, the Yamaha R3 2025 is a perfect fit. While it comes at a slightly premium price, the overall riding experience justifies every penny spent. If you’re in the market for a high-performance yet practical sportbike, the Yamaha R3 2025 is worth considering. FAQs – Yamaha R3 2025 What is the top speed of the Yamaha R3 2025? The Yamaha R3 2025 has a top speed of approximately 180 km/h. What is the fuel efficiency of the Yamaha R3 2025? It offers a mileage of around 25-30 km/l. Does the Yamaha R3 2025 have ABS? Yes, it comes with dual-channel ABS as standard. What is the price of the Yamaha R3 2025 in India? The starting price of the Yamaha R3 2025 is ₹4,65,000 (ex-showroom). How often should I service the Yamaha R3 2025? The first service is at 1,000 km, and then every 5,000 km or 6 months thereafter. Yamha R3 2025 Upcoming Bikes Yamha R3 2025 Upcoming Scooter Yamha R3 2025 Upcoming Cars Yamha R3 2025 Yamaha R3 2025,Yamaha R3 2025 price,Yamaha R3 2025 specs,Yamaha R3 2025 top speed,Yamaha R3 2025 features,Yamaha R3 2025 mileage,Yamaha R3 2025 review,Yamaha R3 2025 vs KTM RC 390,Yamaha R3 2025 maintenance cost,Yamaha R3 2025 service schedule # Yamha R3 2025 Recent Posts - mother motors",
      },
    ],
};
}