export async function getPost1() {
  await new Promise((resolve) => setTimeout(resolve, 0));
  return {
  allpost : [
    { 
      id: 1,
      route: "kawasaki-ninja-250-2025-1403",
      name: "Kawasaki Ninja 250",
      ads: "sports",
      type: "bikes",
      ev: "no",
      price: "₹2,60,000 - ₹3,00,000",
      topspeed: "180",
      mileage: "30-35",
      permileage: "km/l",
      servicecost: "₹3000 - ₹5000",
      specs: "Full Specification of Kawasaki Ninja 250",
      metatitle: "Kawasaki Ninja 250 - A Beginner-Friendly Sports Motorcycle", 
      metadesc: "Kawasaki Ninja 250 review: From top speed to fuel efficiency, features, mileage, pricing and service cost", 
      keywords: ["Kawasaki Ninja 250", "Kawasaki Ninja 250 review", "Kawasaki Ninja 250 price", "Kawasaki Ninja 250 top speed", "Kawasaki Ninja 250 features", "Kawasaki Ninja 250 fuel efficiency", "Kawasaki Ninja 250 mileage", "Kawasaki Ninja 250 pros and cons", "Kawasaki Ninja 250 maintenance", "Kawasaki Ninja 250 service cost"],
      publishedAt: "2025-03-14T12:00:00+05:30",
      modifiedAt:  "2025-03-14T12:00:00+05:30",
      h1: "Kawasaki Ninja 250 – A Beginner-Friendly Sports Motorcycle",
      img: "/bikes/kawasaki-ninja-250-2025-1403.webp",
      subh1: "Kawasaki Ninja 250",
      desc: "The Kawasaki Ninja 250 has long been regarded as one of the best entry-level sportbikes on the market. With its stylish design, nimble handling, and impressive performance, it offers an experience that appeals to both new and experienced riders alike.",
      headingone: "Engine & Performance",
      tableonehead: ["Feature","Specification"],
      tableone: [
          { id: 1,feature: "Engine Type", col1: "Liquid Cooling, 2 Per Cylinder, 8 valves engine"},
          { id: 2,feature: "Displacement", col1: "249 cc"},
          { id: 3,feature: "Max Power", col1: "32 bhp @ 11000 rpm"},
          { id: 4,feature: "Max Toque", col1: "22 Nm @ 8200 rpm"},
          { id: 5,feature: "Bore & Stroke", col1: "62 mm x 41 mm"},
          { id: 6,feature: "Transmission", col1: "6 Speed"},
        ],
      headingtwo: "Braking & Suspension",
      tabletwohead: ["Feature","Specification"],
      tabletwo: [
          { id: 1,feature: "Front Brake", col1: "290 mm, Disc"},
          { id: 2,feature: "Rear Brake", col1: "220 mm, Disc"},
          { id: 3,feature: "Front Suspension", col1: "37 mm Telescopic fork"},
          { id: 4,feature: "Rear Suspension", col1: "Bottom-Link Uni-Trak with gas-charged shock and 5-"},
          { id: 5,feature: "Tyre Size", col1: "110/70-17 M/C (54H) Front, 110/70-17 M/C (54S) Rear"},
        ],
      headingthree: "Dimensions & Chassis",
      tablethreehead: ["Feature","Specification"],
      tablethree: [
          { id: 1,feature: "Frame", col1: "Semi-double cradle, High-tensile steel"},
          { id: 2,feature: "Ground clearance", col1: "135 mm"},
          { id: 3,feature: "Seat Height", col1: "790 mm"},
          { id: 4,feature: "Kerb Weight", col1: "170 kg"},
          { id: 5,feature: "Fuel Tank", col1: "17 litres"},
        ],
        headingfour: "Top Speed & Acceleration of Kawasaki Ninja 250",
        listfourtype : "list-disc",
        listfour: [
          {id: 1, head: "", para: "The Kawasaki Ninja 250 has a top speed of around 180 km/h."},
          {id: 2, head: "", para: "It accelerates from 0 to 60 km/h in approximately 3.5 seconds."},
          {id: 3, head: "", para: "Its acceleration and top speed make it an ideal bike for both city riding and highway cruising."},
        ],
          
        headingfive: "Mileage & Fuel Efficiency of Kawasaki Ninja 250",
        listfivetype : "list-disc",
        listfive: [
          {id: 1, head: "", para: "The Kawasaki Ninja 250 offers a mileage of approximately 30-35 km/l."},
          {id: 2, head: "", para: "Its fuel efficiency makes it a great option for daily commuting."},
          {id: 3, head: "", para: "The fuel tank capacity is around 17 liters, providing good range for long-distance rides."},
        ],
          
      headingsix: " Pricing & all Variants",
      tablesixhead: ["Variants Name","Expected Price (Ex-Showroom)"],
      tablesix: [
          { id: 1,feature: "Kawasaki Ninja 250", col1: "₹2.6 lakh"},
                ],
      listsixtype: "list-disc",
      listsix: [
        {id: 1, head: "", para: "On-Road Price around 3 lakhs"},
      ],
      parasix2: "Note: ",
      parasix3: "Prices may vary based on location and dealer",
  
      headingseven: "Maintenance & Service Cost of Kawasaki Ninja 250",
      listseventype : "list-disc",
      listseven: [
        {id: 1, head: "First Service", para: "The first service is usually required after 1,000 km or 1 month."},
        {id: 2, head: "Second Service", para: "The second service is typically required after 5,000 km."},
        {id: 3, head: "Annual Service", para: "Annual services cost around INR 3,000 to INR 4,000."},
        {id: 4, head: "", para: "Oil changes and minor repairs may cost additional amounts."},
        {id: 5, head: "", para: "Regular maintenance ensures the longevity and smooth performance of the bike."},
      ],
        
      headingeight: "Pros and Cons of Kawasaki Ninja 250",
      listeighttype : "",
      listeight: [
        {id: 1, head: "PROS", para: "1. Excellent fuel efficiency and range."}, 
        {id: 2, head: "", para: "2. Great handling and comfortable for long rides."},
        {id: 3, head: "", para: "3. Affordable pricing compared to other sportbikes."},
        {id: 4, head: "", para: "4. Reliable engine and low maintenance costs."},
        {id: 5, head: "", para: "5. Stylish design with modern features."},
        {id: 6, head: "CONS", para: "1. Lacks some power compared to higher-end sportbikes."},
        {id: 7, head: "", para: "2. Limited pillion seat comfort."},
        {id: 8, head: "", para: "3. Basic instrumentation, lacks advanced features."},
      ],
        
      headingnine: "Kawasaki Ninja 250 Features and Technology",
      listninetype : "list-disc",
      listnine: [
        {id: 1, head: "", para: "Fuel-injected 249cc engine for optimal performance."},
        {id: 2, head: "", para: "Modern digital instrumentation with essential info."},
        {id: 3, head: "", para: "Efficient braking system with dual disc brakes."},
        {id: 4, head: "", para: "Sporty design with aggressive styling and sharp lines."},
        {id: 5, head: "", para: "LED lighting for better visibility."},
        {id: 6, head: "", para: "Comfortable riding position for long rides."},
        {id: 7, head: "", para: "ABS variant for better safety control."},
        {id: 8, head: "", para: "High-quality suspension for smooth riding."},
        {id: 9, head: "", para: "Easy-to-read tachometer and speedometer."},
        {id: 10, head: "", para: "Efficient exhaust system for improved power delivery."},
      ],
        
      headingten: "Kawasaki Ninja 250 User Experience & Review",
      listtentype : "list-disc",
      listten: [
        {id: 1, head: "", para: "The Kawasaki Ninja 250 offers a smooth and enjoyable ride."},
        {id: 2, head: "", para: "Its lightweight build makes it easy to maneuver in city traffic."},
        {id: 3, head: "", para: "The bike's handling is precise, making cornering a breeze."},
        {id: 4, head: "", para: "The engine provides a good mix of power and fuel economy."},
        {id: 5, head: "", para: "Riders have reported good comfort for short to medium distances."},
        {id: 6, head: "", para: "It's an ideal bike for both beginners and experienced riders."},
      ],
        
      paraelten1: "The Kawasaki Ninja 250 stands out as a reliable and fun-to-ride motorcycle. Riders appreciate its manageable power output, making it ideal for those new to sportbikes. ",
      paraelten2: "It’s agile, comfortable, and responsive,",
      paraelten3: " ensuring that each ride is smooth whether you're commuting through the city or cruising on highways. The lightweight design ensures easy handling, while the fuel efficiency keeps running costs low. In addition, the ergonomics are perfect for short to medium distances, making the Ninja 250 a great option for daily commuting.",
      headingeleven: "Why Should You Choose Kawasaki Ninja 250",
      paraeleven1: "The Kawasaki Ninja 250 is an ideal choice for anyone seeking a ",
      paraeleven2: "budget-friendly sportbike that doesn’t compromise on performance.",
      paraeleven3: " It offers a great balance of power, fuel efficiency, and style, making it perfect for beginner and intermediate riders. Whether you’re new to motorcycles or simply want a practical yet fun ride, the Ninja 250 fits perfectly in your garage.",
      paratwelve2: "Its affordable pricing and low maintenance costs",
      paratwelve3: " further elevate its appeal, making it an investment that’s both economical and exciting. With excellent performance and an iconic design, the Ninja 250 is sure to provide countless enjoyable rides.",
      headingthirteen: "Final Verdict on Kawasaki Ninja 250",
      parathirteen1: "The Kawasaki Ninja 250 is a well-rounded motorcycle that offers a fantastic combination of power, handling, and fuel efficiency. Its comfortable ergonomics and easy-to-use performance make it ideal for both new and experienced riders. The Ninja 250 provides a fun riding experience, whether you're taking it through city traffic or exploring winding roads. Additionally,",
      parathirteen2: "its affordable pricing and low maintenance costs",
      parathirteen3: "make it a practical choice for those on a budget.",
  
      headingfourteen: "FAQ for Kawasaki Ninja 250",
      listfourteentype : "list-no",
      listfourteen: [
        {id: 1, head: "What is the top speed of the Kawasaki Ninja 250?", para: "The top speed is around 180 km/h."},
        {id: 2, head: "What is the fuel efficiency of the Ninja 250?", para: "It offers a mileage of 30-35 km/l."},
        {id: 3, head: "How much does the Kawasaki Ninja 250 cost?", para: "The price ranges from INR 2,50,000 to INR 3,00,000."},
        {id: 4, head: "Is the Kawasaki Ninja 250 good for beginners?", para: "Yes, its manageable power makes it perfect for beginner riders."},
        {id: 5, head: "What is the service cost for the Ninja 250?", para: "Service costs range from INR 3,000 to INR 5,000 per service."},
        {id: 6, head: "Does the Ninja 250 have ABS?", para: "Yes, it comes with an ABS variant for added safety."},
        {id: 7, head: "What is the engine capacity of the Ninja 250?", para: "It has a 249cc engine."},
        {id: 8, head: "How reliable is the Kawasaki Ninja 250?", para: "It is highly reliable and known for its low maintenance costs."},
      ],
        
      keysearch: ["Kawasaki Ninja 250", "Kawasaki Ninja 250 review", "Kawasaki Ninja 250 features", "Kawasaki Ninja 250 price", "Kawasaki Ninja 250 mileage", "Kawasaki Ninja 250 top speed", "Kawasaki Ninja 250 pros and cons", "Kawasaki Ninja 250 service cost", "Kawasaki Ninja 250 user review", "Kawasaki Ninja 250 maintenance"],
      full: "Kawasaki Ninja 250 - A Beginner-Friendly Sports Motorcycle March 14, 2025 by Arunzed Kawasaki Ninja 250 The Kawasaki Ninja 250 has long been regarded as one of the best entry-level sportbikes on the market. With its stylish design, nimble handling, and impressive performance, it offers an experience that appeals to both new and experienced riders alike. Kawasaki Ninja 250 ₹2,60,000 - ₹3,00,000 Ex-Showroom Price 180 kmph Top Speed 30-35 km/l Mileage ₹3000 - ₹5000 Serive cost Detail about Pricing, Top Speed, Mileage, service cost is below in this blog Engine & Performance Feature Specification Engine Type Liquid Cooling, 2 Per Cylinder, 8 valves engine Displacement 249 cc Max Power 32 bhp @ 11000 rpm Max Toque 22 Nm @ 8200 rpm Bore & Stroke 62 mm x 41 mm Transmission 6 Speed Braking & Suspension Feature Specification Front Brake 290 mm, Disc Rear Brake 220 mm, Disc Front Suspension 37 mm Telescopic fork Rear Suspension Bottom-Link Uni-Trak with gas-charged shock and 5- Tyre Size 110/70-17 M/C (54H) Front, 110/70-17 M/C (54S) Rear Dimensions & Chassis Feature Specification Frame Semi-double cradle, High-tensile steel Ground clearance 135 mm Seat Height 790 mm Kerb Weight 170 kg Fuel Tank 17 litres Top Speed & Acceleration of Kawasaki Ninja 250 The Kawasaki Ninja 250 has a top speed of around 180 km/h. It accelerates from 0 to 60 km/h in approximately 3.5 seconds. Its acceleration and top speed make it an ideal bike for both city riding and highway cruising. Mileage & Fuel Efficiency of Kawasaki Ninja 250 The Kawasaki Ninja 250 offers a mileage of approximately 30-35 km/l. Its fuel efficiency makes it a great option for daily commuting. The fuel tank capacity is around 17 liters, providing good range for long-distance rides. Pricing & all Variants Variants Name Expected Price (Ex-Showroom) Kawasaki Ninja 250 ₹2.6 lakh On-Road Price around 3 lakhs Note: Prices may vary based on location and dealer Maintenance & Service Cost of Kawasaki Ninja 250 First Service The first service is usually required after 1,000 km or 1 month. Second Service The second service is typically required after 5,000 km. Annual Service Annual services cost around INR 3,000 to INR 4,000. Oil changes and minor repairs may cost additional amounts. Regular maintenance ensures the longevity and smooth performance of the bike. Pros and Cons of Kawasaki Ninja 250 PROS 1. Excellent fuel efficiency and range. 2. Great handling and comfortable for long rides. 3. Affordable pricing compared to other sportbikes. 4. Reliable engine and low maintenance costs. 5. Stylish design with modern features. CONS 1. Lacks some power compared to higher-end sportbikes. 2. Limited pillion seat comfort. 3. Basic instrumentation, lacks advanced features. Kawasaki Ninja 250 Features and Technology Fuel-injected 249cc engine for optimal performance. Modern digital instrumentation with essential info. Efficient braking system with dual disc brakes. Sporty design with aggressive styling and sharp lines. LED lighting for better visibility. Comfortable riding position for long rides. ABS variant for better safety control. High-quality suspension for smooth riding. Easy-to-read tachometer and speedometer. Efficient exhaust system for improved power delivery. Kawasaki Ninja 250 User Experience & Review The Kawasaki Ninja 250 offers a smooth and enjoyable ride. Its lightweight build makes it easy to maneuver in city traffic. The bike's handling is precise, making cornering a breeze. The engine provides a good mix of power and fuel economy. Riders have reported good comfort for short to medium distances. It's an ideal bike for both beginners and experienced riders. Why Should You Choose Kawasaki Ninja 250 The Kawasaki Ninja 250 is an ideal choice for anyone seeking a budget-friendly sportbike that doesn’t compromise on performance. It offers a great balance of power, fuel efficiency, and style, making it perfect for beginner and intermediate riders. Whether you’re new to motorcycles or simply want a practical yet fun ride, the Ninja 250 fits perfectly in your garage. Its affordable pricing and low maintenance costs further elevate its appeal, making it an investment that’s both economical and exciting. With excellent performance and an iconic design, the Ninja 250 is sure to provide countless enjoyable rides. Final Verdict on Kawasaki Ninja 250 The Kawasaki Ninja 250 is a well-rounded motorcycle that offers a fantastic combination of power, handling, and fuel efficiency. Its comfortable ergonomics and easy-to-use performance make it ideal for both new and experienced riders. The Ninja 250 provides a fun riding experience, whether you're taking it through city traffic or exploring winding roads. Additionally, its affordable pricing and low maintenance costs make it a practical choice for those on a budget. FAQ for Kawasaki Ninja 250 1. What is the top speed of the Kawasaki Ninja 250? The top speed is around 180 km/h. 2. What is the fuel efficiency of the Ninja 250? It offers a mileage of 30-35 km/l. 3. How much does the Kawasaki Ninja 250 cost? The price ranges from INR 2,50,000 to INR 3,00,000. 4. Is the Kawasaki Ninja 250 good for beginners? Yes, its manageable power makes it perfect for beginner riders. 5. What is the service cost for the Ninja 250? Service costs range from INR 3,000 to INR 5,000 per service. 6. Does the Ninja 250 have ABS? Yes, it comes with an ABS variant for added safety. 7. What is the engine capacity of the Ninja 250? It has a 249cc engine. 8. How reliable is the Kawasaki Ninja 250? It is highly reliable and known for its low maintenance costs.",
  },
  
  
  
  ],
};
}